1:
  firstName: "Jane"
  lastName: "Doe"
  hiredDate: "1/2/2014"
  phone: "555-234-3455"
  email: "jdoe@fakecomp.com"
  department: "Infrastructure"
3:
  firstName: "Sammy"
  lastName: "Dean"
  hiredDate: "1/2/2014"
  phone: "555-454-3456"
  email: "sdean@fakecomp.com"
  department: "Sales"
12:
  firstName: "Bob"
  lastName: "Smith"
  hiredDate: "12/21/2018"
  phone: "555-434-5345"
  email: "bsmith@fakecomp.com"
  department: "Infrastructure"
17:
  firstName: "Emanuel"
  lastName: "Jones"
  hiredDate: "1/24/2014"
  phone: "555-764-8767"
  email: "ejones@fakecomp.com"
  department: "Accounting"
18:
  firstName: "Sandy"
  lastName: "Melone"
  hiredDate: "1/2/2014"
  phone: "555-665-3456"
  email: "smalone@fakecomp.com"
  department: "Helpdesk"
27:
  firstName: "Jimmy"
  lastName: "Simms"
  hiredDate: "1/12/2014"
  phone: "555-566-6768"
  email: "jsimms@fakecomp.com"
36:
  firstName: "Joana"
  lastName: "Ming"
  hiredDate: "11/24/2019"
  phone: "555-827-8579"
  email: "jming@fakecomp.com"
  department: "Sales"